import mongoose, { Schema } from 'mongoose';
const siteSettingsSchema = new Schema({
    key: { type: String, required: true, unique: true, default: 'default' },
    phone: { type: String, required: true, default: '+91 9990069939' },
    email: { type: String, required: true, default: 'Join1percent.in@gmail.com' },
    domainName: { type: String, required: true, default: 'join1percent.in' },
    siteName: { type: String, required: true, default: 'Join1Percent' },
    address: { type: String, required: true, default: 'Indiranagar 100ft Road, Bengaluru, Karnataka 560038' },
    copyright: { type: String, required: true, default: '© 2026 Join1Percent. All Rights Reserved.' },
    mapEmbed: {
        type: String,
        required: true,
        default: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.9946890333333!2d77.6387!3d12.9719!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae16a6bb7c2645%3A0x6d116c4f74d081f2!2sIndiranagar%20100ft%20Rd%2C%20Bengaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
    },
    logoUrl: { type: String, required: false, default: '' },
    popup: {
        isEnabled: { type: Boolean, default: false },
        contentType: { type: String, enum: ['image', 'embedVideo', 'video', 'html', 'form'], default: 'image' },
        title: { type: String, default: 'Special Offer' },
        imageContent: { type: String, default: '' },
        imageLink: { type: String, default: '' },
        videoContent: { type: String, default: '' },
        htmlContent: { type: String, default: '' },
        formTitle: { type: String, default: 'Join Our Newsletter' },
        formButtonText: { type: String, default: 'Submit' },
    },
    hero: {
        badge: { type: String, default: 'LEARN • BUILD • GROW' },
        titlePrefix: { type: String, default: 'Skills that' },
        titleHighlight: { type: String, default: 'move you forward.' },
        description: {
            type: String,
            default: 'Learn practical skills from courses designed for the way people actually work today. AI orchestration, full-stack systems, performance growth, and high-ticket consulting.',
        },
        primaryBtnText: { type: String, default: 'View Plans' },
        primaryBtnLink: { type: String, default: '#plans' },
        secondaryBtnText: { type: String, default: 'Explore courses' },
        secondaryBtnLink: { type: String, default: '#plans' },
        learnersCount: { type: String, default: '10,000+' },
        coursesCount: { type: String, default: '50+' },
        ratingText: { type: String, default: '4.9/5' },
        featuredCourseSlug: { type: String, default: '' },
        featuredBadge: { type: String, default: 'Featured Masterclass' },
        featuredTag: { type: String, default: '24 Lessons • 8.5h' },
        featuredCategory: { type: String, default: 'AI & Engineering' },
        featuredLevel: { type: String, default: 'Intermediate' },
        featuredRating: { type: String, default: '4.92' },
        featuredReviewsCount: { type: String, default: '1,840 reviews' },
        featuredTitle: { type: String, default: 'Modern Generative AI & Agent Workflows' },
        featuredDescription: {
            type: String,
            default: 'Master prompt orchestration, function-calling pipelines, RAG architecture, and production agent deployment with real TypeScript & Python code.',
        },
        featuredImage: {
            type: String,
            default: 'https://courses.iid.org.in/public//uploads/media_manager/628.jpg',
        },
        featuredVideoUrl: {
            type: String,
            default: 'https://www.youtube.com/watch?v=kCc8FmEb1nY',
        },
        featuredLessonTitle: {
            type: String,
            default: 'Lesson 03: Autonomous Tool-Calling & Structured Outputs',
        },
        featuredLessonDuration: { type: String, default: '18:45' },
        instructorName: { type: String, default: 'Aravind Nair' },
        instructorRole: { type: String, default: 'Staff AI Engineer • Ex-Stripe' },
        instructorAvatar: {
            type: String,
            default: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
        },
    },
}, { timestamps: true });
export const SiteSettings = mongoose.models.SiteSettings ||
    mongoose.model('SiteSettings', siteSettingsSchema);
export const DEFAULT_HERO_SETTINGS = {
    badge: 'LEARN • BUILD • GROW',
    titlePrefix: 'Skills that',
    titleHighlight: 'move you forward.',
    description: 'Learn practical skills from courses designed for the way people actually work today. AI orchestration, full-stack systems, performance growth, and high-ticket consulting.',
    primaryBtnText: 'View Plans',
    primaryBtnLink: '#plans',
    secondaryBtnText: 'Explore courses',
    secondaryBtnLink: '#plans',
    learnersCount: '10,000+',
    coursesCount: '50+',
    ratingText: '4.9/5',
    featuredCourseSlug: '',
    featuredBadge: 'Featured Masterclass',
    featuredTag: '24 Lessons • 8.5h',
    featuredCategory: 'AI & Engineering',
    featuredLevel: 'Intermediate',
    featuredRating: '4.92',
    featuredReviewsCount: '1,840 reviews',
    featuredTitle: 'Modern Generative AI & Agent Workflows',
    featuredDescription: 'Master prompt orchestration, function-calling pipelines, RAG architecture, and production agent deployment with real TypeScript & Python code.',
    featuredImage: 'https://courses.iid.org.in/public//uploads/media_manager/628.jpg',
    featuredVideoUrl: 'https://www.youtube.com/watch?v=kCc8FmEb1nY',
    featuredLessonTitle: 'Lesson 03: Autonomous Tool-Calling & Structured Outputs',
    featuredLessonDuration: '18:45',
    instructorName: 'Aravind Nair',
    instructorRole: 'Staff AI Engineer • Ex-Stripe',
    instructorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
};
export const DEFAULT_SITE_SETTINGS = {
    phone: '+91 9990069939',
    email: 'Join1percent.in@gmail.com',
    domainName: 'join1percent.in',
    siteName: 'Join1Percent',
    address: 'Indiranagar 100ft Road, Bengaluru, Karnataka 560038',
    copyright: '© 2026 Join1Percent. All Rights Reserved.',
    mapEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3887.9946890333333!2d77.6387!3d12.9719!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae16a6bb7c2645%3A0x6d116c4f74d081f2!2sIndiranagar%20100ft%20Rd%2C%20Bengaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
    logoUrl: '',
    popup: {
        isEnabled: false,
        contentType: 'image',
        title: 'Special Offer',
        imageContent: '',
        imageLink: '',
        videoContent: '',
        htmlContent: '',
        formTitle: 'Join Our Newsletter',
        formButtonText: 'Submit',
    },
    hero: DEFAULT_HERO_SETTINGS,
};
